### PR TITLE
Add CI checks via GitHub Actions

### PR DESCRIPTION
**Pull request by coatless**
Enable CI on commits to ensure build quality via GitHub Actions.

Action configuration is based on:

https://github.com/r-lib/actions/blob/630f4c9d8b813f45d0327a2fc20eb264fd518450/examples/check-standard.yaml

### CODE REVIEW

**Comment by pdbailey0** [comment]
This one seems like it would be useful, but our tests require too many manual downloads where the user must click to accept a license for us to test on a remote machine.

**Comment by coatless** [comment]
@pdbailey0 this was only applying `R CMD check`-style tests, e.g. what CRAN does. The action was not designed to run through the `testthat` unit tests in `tests/`. I would encourage you to try this out. Though, there has been an update or two since I submitted this PR.

**Comment by coatless** [comment]
@pdbailey0 updated to the latest action from r-lib/actions. 

I commented out the `testthat` portion.

**Comment by pdbailey0** [comment]
Is there a way I can see this in action? Also, did my readme need to get removed?

**Comment by coatless** [comment]
@pdbailey0 no, the README was an unintentional victim of the merge conflict hiccup. 

You can see an example of the action working here: 

https://github.com/tmsalab/edmdata/pull/24/checks?check_run_id=3706762525

**Pull request merged**
